---
apiVersion: v1
kind: Namespace
metadata:
  name: rabbitmq
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: rabbitmq-configmap
  namespace: rabbitmq
data:
  RABBITMQ_VM_MEMORY_HIGH_WATERMARK: "0.6"
---
apiVersion: v1
kind: Service
metadata:
  name: rabbitmq-service
  namespace: rabbitmq
spec:
  ports:
  - name: http
    nodePort: 30672
    port: 15672
    protocol: TCP
    targetPort: 15672
  - name: amqp
    nodePort: 31672
    port: 5672
    protocol: TCP
    targetPort: 5672
  selector:
    app: rabbitmq
  type: NodePort
---
apiVersion: apps/v1
# TODO: rewrite as a StatefulSet
kind: Deployment
metadata:
  name: rabbitmq
  namespace: rabbitmq
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rabbitmq
  template:
    metadata:
      labels:
        app: rabbitmq
    spec:
      containers:
      - name: rabbitmq
        image: rabbitmq:management
        ports:
        - containerPort: 4369
        - containerPort: 5672
        - containerPort: 25672
        - containerPort: 15672
